apiVersion: v1
kind: ConfigMap
metadata:
  name: lfx-config
  namespace: team-lfx
data:
  allowed: '"true"'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alt-config
  namespace: team-lfx
  labels:
    lfx-mentorship: not-kyverno
data:
  allowed: '"true"'